
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const rad=d=>d*Math.PI/180; const deg=r=>r*180/Math.PI;
const deep=o=>structuredClone(o); const uid=()=>Math.random().toString(36).slice(2,10);
const state={manifest:[],project:null,sourceCase:null,selectedBone:null,currentTime:0,playing:false,lastT:0,speed:1,fps:30,loop:true,showGrid:true,showNames:false,onion:false,leftTab:'cases',insTab:'bone',view:{x:0,y:0,zoom:1},drag:null,history:[],future:[],overrides:{},snapshots:[],reference:null};
const canvas=$('#stage'),ctx=canvas.getContext('2d');

const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('rig-motion-lab',1);r.onupgradeneeded=()=>{r.result.createObjectStore('projects',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function dbPut(p){const db=await dbp;return new Promise((res,rej)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(p);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function dbAll(){const db=await dbp;return new Promise((res,rej)=>{const q=db.transaction('projects').objectStore('projects').getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbGet(id){const db=await dbp;return new Promise((res,rej)=>{const q=db.transaction('projects').objectStore('projects').get(id);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}

function normalizeProject(data,name='未命名工程'){
 const bones=(data.bones||[]).map((b,i)=>({name:b.name||`bone_${i}`,parent:b.parent||null,length:+b.length||0,x:+b.x||0,y:+b.y||0,rotation:+b.rotation||0,scaleX:b.scaleX==null?1:+b.scaleX,scaleY:b.scaleY==null?1:+b.scaleY,shearX:+b.shearX||0,shearY:+b.shearY||0,transform:b.transform||'normal',hidden:false,locked:false}));
 const animations=data.animations||{}; const durations=data.durations||Object.fromEntries(Object.entries(animations).map(([n,a])=>[n,measureDuration(a)]));
 return {id:data.id||uid(),name:data.name||name,createdAt:data.createdAt||Date.now(),updatedAt:Date.now(),schema:'rig-motion-lab/project@2',source:data.source||{},skeleton:data.skeleton||{},bones,ik:data.ik||[],transform:data.transform||[],path:data.path||[],animations,durations,activeAnimation:data.activeAnimation||Object.keys(animations)[0]||'Setup Pose',customKeys:data.customKeys||{},notes:data.notes||'',tags:data.tags||[]};
}
function measureDuration(a){let mx=0;const stack=[a];while(stack.length){const x=stack.pop();if(Array.isArray(x)) stack.push(...x);else if(x&&typeof x==='object'){if(typeof x.time==='number')mx=Math.max(mx,x.time);stack.push(...Object.values(x))}}return mx}
function pushHistory(){if(!state.project)return;state.history.push(JSON.stringify({bones:state.project.bones,customKeys:state.project.customKeys}));if(state.history.length>60)state.history.shift();state.future=[]}
function undo(){if(!state.history.length||!state.project)return;state.future.push(JSON.stringify({bones:state.project.bones,customKeys:state.project.customKeys}));const x=JSON.parse(state.history.pop());state.project.bones=x.bones;state.project.customKeys=x.customKeys;renderAll()}
function redo(){if(!state.future.length||!state.project)return;state.history.push(JSON.stringify({bones:state.project.bones,customKeys:state.project.customKeys}));const x=JSON.parse(state.future.pop());state.project.bones=x.bones;state.project.customKeys=x.customKeys;renderAll()}

async function loadManifest(){try{const r=await fetch('data/cases.json',{cache:'no-store'});state.manifest=(await r.json()).cases||[]}catch(e){console.error(e)}renderLeft()}
async function loadCase(c){const b64=window.RIG_CASE_PACK?.[c.id];if(!b64)throw new Error('案例数据不存在: '+c.id);const bin=Uint8Array.from(atob(b64),x=>x.charCodeAt(0));const raw=pako.ungzip(bin,{to:'string'});const d=JSON.parse(raw);state.sourceCase=c;state.project=normalizeProject({...d,name:c.title,id:'case-'+c.id},c.title);state.project.activeAnimation=state.project.animations.Idle?'Idle':Object.keys(state.project.animations)[0]||'Setup Pose';state.currentTime=0;state.selectedBone=state.project.bones[0]?.name||null;state.history=[];state.future=[];fitView();renderAll()}
function loadProject(p){state.project=normalizeProject(p,p.name);state.sourceCase=null;state.currentTime=0;state.selectedBone=state.project.bones[0]?.name||null;state.history=[];state.future=[];fitView();renderAll()}

function timelineFrames(anim,bone,type){return anim?.bones?.[bone]?.[type]||[]}
function bezierEase(t,c){if(!Array.isArray(c)||c.length<4)return t;const [x1,y1,x2,y2]=c;let lo=0,hi=1,u=t;for(let i=0;i<10;i++){u=(lo+hi)/2;const x=3*(1-u)*(1-u)*u*x1+3*(1-u)*u*u*x2+u*u*u;if(x<t)lo=u;else hi=u}return 3*(1-u)*(1-u)*u*y1+3*(1-u)*u*u*y2+u*u*u}
function sampleFrames(frames,t,keys,defaults){if(!frames?.length)return defaults;let a=frames[0],b=null;if(t<=+a.time||0)b=a;else{for(let i=0;i<frames.length-1;i++){if(t>=frames[i].time&&t<frames[i+1].time){a=frames[i];b=frames[i+1];break}}if(!b){a=frames[frames.length-1];b=a}}
 if(a===b)return Object.fromEntries(keys.map((k,i)=>[k,a[k]??defaults[k]??0]));const span=b.time-a.time||1;let u=clamp((t-a.time)/span,0,1);if(a.curve==='stepped')u=0;else if(Array.isArray(a.curve))u=bezierEase(u,a.curve);const out={};for(const k of keys){const av=+(a[k]??defaults[k]??0),bv=+(b[k]??av);out[k]=av+(bv-av)*u}return out}
function customFor(name,t){const arr=state.project?.customKeys?.[state.project.activeAnimation]?.[name]||[];if(!arr.length)return null;let best=null;for(const k of arr)if(k.time<=t+1e-4)best=k;return best}
function localPose(t){if(!state.project)return[];const anim=state.project.animations[state.project.activeAnimation];return state.project.bones.map(b=>{let p={...b};if(anim){const ro=sampleFrames(timelineFrames(anim,b.name,'rotate'),t,['angle'],{angle:0});p.rotation=b.rotation+ro.angle;const tr=sampleFrames(timelineFrames(anim,b.name,'translate'),t,['x','y'],{x:0,y:0});p.x=b.x+tr.x;p.y=b.y+tr.y;const sc=sampleFrames(timelineFrames(anim,b.name,'scale'),t,['x','y'],{x:1,y:1});if(timelineFrames(anim,b.name,'scale').length){p.scaleX=b.scaleX*sc.x;p.scaleY=b.scaleY*sc.y}const sh=sampleFrames(timelineFrames(anim,b.name,'shear'),t,['x','y'],{x:0,y:0});p.shearX=b.shearX+sh.x;p.shearY=b.shearY+sh.y}
 const c=customFor(b.name,t);if(c)Object.assign(p,c.pose);return p})}
function worldPose(t){const loc=localPose(t),map=new Map(),out=[];for(const b of loc){let wx=b.x,wy=b.y,wr=b.rotation,wsx=b.scaleX,wsy=b.scaleY;if(b.parent&&map.has(b.parent)){const p=map.get(b.parent),r=rad(p.wr);wx=p.wx+Math.cos(r)*b.x*p.wsx-Math.sin(r)*b.y*p.wsy;wy=p.wy+Math.sin(r)*b.x*p.wsx+Math.cos(r)*b.y*p.wsy;wr=p.wr+b.rotation;wsx=p.wsx*b.scaleX;wsy=p.wsy*b.scaleY}const w={...b,wx,wy,wr,wsx,wsy};map.set(b.name,w);out.push(w)}return out}

function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1;const w=Math.max(1,Math.floor(r.width*d)),h=Math.max(1,Math.floor(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;ctx.setTransform(d,0,0,d,0,0)}}
function toScreen(x,y){const r=canvas.getBoundingClientRect();return [r.width/2+state.view.x+x*state.view.zoom,r.height/2+state.view.y-y*state.view.zoom]}
function toWorld(x,y){const r=canvas.getBoundingClientRect();return [(x-r.width/2-state.view.x)/state.view.zoom,-(y-r.height/2-state.view.y)/state.view.zoom]}
function drawGrid(){if(!state.showGrid)return;const r=canvas.getBoundingClientRect(),z=state.view.zoom;let step=20;while(step*z<30)step*=2;while(step*z>100)step/=2;ctx.save();ctx.strokeStyle='#151b24';ctx.lineWidth=1;const [wx0,wy0]=toWorld(0,r.height),[wx1,wy1]=toWorld(r.width,0);for(let x=Math.floor(wx0/step)*step;x<=wx1;x+=step){const [sx]=toScreen(x,0);ctx.beginPath();ctx.moveTo(sx,0);ctx.lineTo(sx,r.height);ctx.stroke()}for(let y=Math.floor(wy0/step)*step;y<=wy1;y+=step){const [,sy]=toScreen(0,y);ctx.beginPath();ctx.moveTo(0,sy);ctx.lineTo(r.width,sy);ctx.stroke()}const [ox,oy]=toScreen(0,0);ctx.strokeStyle='#273247';ctx.beginPath();ctx.moveTo(ox,0);ctx.lineTo(ox,r.height);ctx.moveTo(0,oy);ctx.lineTo(r.width,oy);ctx.stroke();ctx.restore()}
function drawPose(pose,alpha=1,ghost=false){const sel=state.selectedBone;ctx.save();ctx.globalAlpha=alpha;for(const b of pose){if(b.hidden)continue;const [x,y]=toScreen(b.wx,b.wy),rr=rad(b.wr);const ex=b.wx+Math.cos(rr)*b.length*b.wsx,ey=b.wy+Math.sin(rr)*b.length*b.wsx,[x2,y2]=toScreen(ex,ey);ctx.lineCap='round';ctx.lineWidth=ghost?2:3;ctx.strokeStyle=ghost?'#5b7596':(b.name===sel?'#ffd43b':'#7891ad');ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();ctx.fillStyle=b.name===sel?'#ffd43b':'#c4d2e1';ctx.beginPath();ctx.arc(x,y,b.name===sel?5:3.2,0,Math.PI*2);ctx.fill();if(state.showNames&&!ghost){ctx.font='10px var(--mono)';ctx.fillStyle='#aeb9c8';ctx.fillText(b.name,x+6,y-6)}}ctx.restore()}
function draw(){resizeCanvas();const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#0c0f14';ctx.fillRect(0,0,r.width,r.height);drawGrid();if(state.project){if(state.onion){const f=1/state.fps;drawPose(worldPose(Math.max(0,state.currentTime-f)),.18,true);drawPose(worldPose(Math.min(duration(),state.currentTime+f)),.18,true)}drawPose(worldPose(state.currentTime),1,false);if(state.reference?.pose)drawPose(state.reference.pose,.26,true)}requestAnimationFrame(draw)}
function hitBone(sx,sy){if(!state.project)return null;let best=null,bd=14;for(const b of worldPose(state.currentTime)){const [x,y]=toScreen(b.wx,b.wy),d=Math.hypot(x-sx,y-sy);if(d<bd){best=b;bd=d}}return best}
function duration(){return state.project?.durations?.[state.project.activeAnimation]??measureDuration(state.project?.animations?.[state.project?.activeAnimation]||{})??0}
function fitView(){if(!state.project)return;const p=worldPose(state.currentTime);if(!p.length)return;let xs=[],ys=[];for(const b of p){xs.push(b.wx);ys.push(b.wy);const rr=rad(b.wr);xs.push(b.wx+Math.cos(rr)*b.length);ys.push(b.wy+Math.sin(rr)*b.length)}const minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);const r=canvas.getBoundingClientRect();state.view.zoom=clamp(Math.min((r.width-120)/(maxx-minx||100),(r.height-120)/(maxy-miny||100)),.15,8);state.view.x=-(minx+maxx)/2*state.view.zoom;state.view.y=(miny+maxy)/2*state.view.zoom}

function renderAll(){renderLeft();renderInspector();renderTimeline();renderAnimSelect();renderMeta()}
function renderMeta(){if(!state.project){$('#footProject').textContent='未加载工程';$('#hud').textContent='选择案例或新建工程';return}const d=duration();$('#timeRange').max=d||1;$('#timeRange').value=state.currentTime;$('#timeLabel').textContent=`${state.currentTime.toFixed(3)} / ${d.toFixed(3)}`;$('#footProject').textContent=`${state.project.name} · ${state.project.bones.length} bones`;$('#hud').textContent=`${state.project.activeAnimation}  |  t ${state.currentTime.toFixed(3)}s  |  ${(state.currentTime*state.fps).toFixed(0)}f  |  zoom ${(state.view.zoom*100).toFixed(0)}%`;$('#playBtn').textContent=state.playing?'❚❚':'▶'}
function renderAnimSelect(){const s=$('#animSelect');if(!state.project){s.innerHTML='<option>无动画</option>';return}const names=Object.keys(state.project.animations);s.innerHTML=(names.length?names:['Setup Pose']).map(n=>`<option ${n===state.project.activeAnimation?'selected':''}>${esc(n)}</option>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function renderLeft(){const q=$('#leftSearch').value?.trim().toLowerCase()||'',pane=$('#leftPane');if(state.leftTab==='cases'){const list=state.manifest.filter(c=>(c.title+' '+c.animations.join(' ')).toLowerCase().includes(q));pane.innerHTML=`<div class="section-title"><span>仓库案例 ${list.length}</span><span class="badge">Spine 3.5</span></div>`+list.map(c=>`<div class="case-card ${state.sourceCase?.id===c.id?'active':''}" data-case="${c.id}"><div class="case-title">${esc(c.title)}</div><div class="case-meta"><span class="badge">${c.bones} bones</span><span class="badge">${c.animations.length} clips</span><span class="badge">${esc(c.view)}</span></div></div>`).join('')+`<div class="drop" id="dropZone">拖入 Spine JSON / ZIP<br>导入为新工程</div>`;$$('[data-case]').forEach(el=>el.onclick=()=>loadCase(state.manifest.find(c=>c.id===el.dataset.case)));setupDrop();return}
 if(state.leftTab==='bones'){if(!state.project){pane.innerHTML='<div class="empty">先加载一个工程</div>';return}const bones=state.project.bones,children=new Map();bones.forEach(b=>{if(!children.has(b.parent))children.set(b.parent,[]);children.get(b.parent).push(b)});let html='<div class="section-title"><span>骨骼层级</span><button id="addBoneSmall">＋</button></div>';function walk(parent,depth){for(const b of children.get(parent)||[]){if(!b.name.toLowerCase().includes(q)&&q){}else html+=`<div class="tree-row ${b.name===state.selectedBone?'active':''}" data-bone="${esc(b.name)}" style="padding-left:${depth*13}px"><span class="tw">${(children.get(b.name)||[]).length?'›':''}</span><span class="bone-dot"></span><span class="name">${esc(b.name)}</span>${b.locked?'🔒':''}${b.hidden?'◌':''}</div>`;walk(b.name,depth+1)}}walk(null,0);pane.innerHTML=html;$$('[data-bone]').forEach(el=>el.onclick=()=>{state.selectedBone=el.dataset.bone;renderLeft();renderInspector();renderTimeline()});$('#addBoneSmall').onclick=addBone;return}
 dbAll().then(items=>{pane.innerHTML='<div class="section-title"><span>本地工程</span><span>'+items.length+'</span></div>'+items.filter(x=>x.name.toLowerCase().includes(q)).map(p=>`<div class="case-card" data-project="${p.id}"><div class="case-title">${esc(p.name)}</div><div class="case-meta"><span class="badge">${p.bones?.length||0} bones</span><span>${new Date(p.updatedAt||p.createdAt).toLocaleString()}</span></div></div>`).join('')+'<div class="note">工程保存在当前浏览器 IndexedDB。使用“导出”可生成可迁移的工程 JSON。</div>';$$('[data-project]').forEach(el=>el.onclick=async()=>loadProject(await dbGet(el.dataset.project)))})}

function selected(){return state.project?.bones.find(b=>b.name===state.selectedBone)}
function renderInspector(){const p=$('#insPane');if(!state.project){p.innerHTML='<div class="empty">暂无工程</div>';return}if(state.insTab==='bone'){const b=selected();if(!b){p.innerHTML='<div class="empty">选择一根骨骼</div>';return}p.innerHTML=`<div class="section-title"><span>${esc(b.name)}</span><span class="badge">${esc(b.parent||'root')}</span></div>${numField('X','x',b.x)}${numField('Y','y',b.y)}${numField('旋转','rotation',b.rotation)}${numField('长度','length',b.length)}${numField('Scale X','scaleX',b.scaleX)}${numField('Scale Y','scaleY',b.scaleY)}<div class="field"><label>父骨骼</label><select id="parentField"><option value="">— root —</option>${state.project.bones.filter(x=>x.name!==b.name).map(x=>`<option ${b.parent===x.name?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="toolbar-row"><button id="keyBone">◆ 当前帧</button><button id="dupBone">复制</button><button id="lockBone">${b.locked?'解锁':'锁定'}</button><button id="hideBone">${b.hidden?'显示':'隐藏'}</button><button id="delBone" class="danger">删除</button></div><div class="section-title"><span>Setup / Pose</span></div><div class="toolbar-row"><button id="resetBone">重设此骨</button><button id="mirrorPose">镜像姿态</button></div>`;$$('[data-prop]').forEach(i=>i.onchange=()=>{pushHistory();b[i.dataset.prop]=+i.value||0;renderTimeline()});$('#parentField').onchange=e=>{pushHistory();b.parent=e.target.value||null};$('#keyBone').onclick=addCurrentKey;$('#dupBone').onclick=duplicateBone;$('#lockBone').onclick=()=>{b.locked=!b.locked;renderInspector();renderLeft()};$('#hideBone').onclick=()=>{b.hidden=!b.hidden;renderInspector();renderLeft()};$('#delBone').onclick=deleteBone;$('#resetBone').onclick=()=>{state.project.customKeys[state.project.activeAnimation]&&(state.project.customKeys[state.project.activeAnimation][b.name]=[]);renderAll()};$('#mirrorPose').onclick=mirrorPose;return}
 if(state.insTab==='clip'){const a=state.project.activeAnimation,d=duration(),anim=state.project.animations[a]||{};const keyed=Object.keys(anim.bones||{}).length;p.innerHTML=`<div class="section-title"><span>动画片段</span><span class="badge">${esc(a)}</span></div><div class="metric"><span>时长</span><span>${d.toFixed(3)} s</span></div><div class="metric"><span>帧数 @ ${state.fps}fps</span><span>${Math.ceil(d*state.fps)}</span></div><div class="metric"><span>动画骨骼</span><span>${keyed}</span></div><div class="metric"><span>IK 约束</span><span>${state.project.ik.length}</span></div><div class="metric"><span>Transform 约束</span><span>${state.project.transform.length}</span></div><div class="field"><label>循环</label><select id="loopField"><option value="1" ${state.loop?'selected':''}>是</option><option value="0" ${!state.loop?'selected':''}>否</option></select></div><div class="toolbar-row"><button id="snapshotBtn">姿态快照</button><button id="setRefBtn">设为参考</button></div><div class="section-title"><span>工程信息</span></div><div class="note">来源：${esc(state.project.source?.name||'自建工程')}<br>Spine：${esc(state.project.source?.spine||state.project.skeleton?.spine||'—')}<br>工作室使用非破坏式覆盖关键帧，不改写原始案例文件。</div>`;$('#loopField').onchange=e=>state.loop=e.target.value==='1';$('#snapshotBtn').onclick=makeSnapshot;$('#setRefBtn').onclick=()=>{state.reference={pose:deep(worldPose(state.currentTime)),name:a+' @ '+state.currentTime.toFixed(3)};renderInspector()};return}
 const score=state.reference?poseScore():null;p.innerHTML=`<div class="section-title"><span>训练模式</span><span class="badge">Pose Match</span></div>${state.reference?`<div class="score">${score}%</div><div class="note">参考：${esc(state.reference.name)}<br>基于同名骨骼的关节位置与旋转误差评分。</div><div class="toolbar-row"><button id="clearRef">清除参考</button><button id="saveTrain">记录本次</button></div>`:`<div class="note">在“动画”页把任意时刻设为参考姿态，然后修改/创建姿态并实时比较。</div>`}<div class="section-title"><span>训练工具</span></div><div class="toolbar-row"><button id="randomTime">随机参考帧</button><button id="hideNamesTrain">隐藏骨名</button><button id="toggleOnionTrain">洋葱皮</button></div>`;if($('#clearRef'))$('#clearRef').onclick=()=>{state.reference=null;renderInspector()};if($('#randomTime'))$('#randomTime').onclick=()=>{state.currentTime=Math.random()*duration();state.reference={pose:deep(worldPose(state.currentTime)),name:state.project.activeAnimation+' 随机帧'};renderMeta();renderInspector()};if($('#hideNamesTrain'))$('#hideNamesTrain').onclick=()=>state.showNames=false;if($('#toggleOnionTrain'))$('#toggleOnionTrain').onclick=()=>state.onion=!state.onion}
function numField(label,prop,val){return `<div class="field"><label>${label}</label><input data-prop="${prop}" type="number" step="0.1" value="${(+val||0).toFixed(3)}"></div>`}

function renderTimeline(){const box=$('#tracks');if(!state.project){box.innerHTML='';return}const anim=state.project.animations[state.project.activeAnimation],d=duration()||1,bones=state.project.bones.filter(b=>anim?.bones?.[b.name]||state.project.customKeys?.[state.project.activeAnimation]?.[b.name]);let html='';for(const b of bones.slice(0,100)){const times=new Set();for(const arr of Object.values(anim?.bones?.[b.name]||{}))if(Array.isArray(arr))arr.forEach(k=>times.add(+k.time||0));(state.project.customKeys?.[state.project.activeAnimation]?.[b.name]||[]).forEach(k=>times.add(k.time));html+=`<div class="track"><div class="track-label">${esc(b.name)}</div><div class="track-lane" data-lane="${esc(b.name)}">${[...times].sort((a,z)=>a-z).map(t=>`<i class="kf" style="left:${clamp(t/d*100,0,100)}%" title="${t.toFixed(3)}"></i>`).join('')}<i class="playhead" style="left:${clamp(state.currentTime/d*100,0,100)}%"></i></div></div>`}box.innerHTML=html||'<div class="empty">当前片段没有骨骼关键帧</div>';$$('[data-lane]').forEach(l=>l.onclick=e=>{const r=l.getBoundingClientRect();state.currentTime=clamp((e.clientX-r.left)/r.width*d,0,d);state.selectedBone=l.dataset.lane;renderMeta();renderTimeline();renderInspector()});renderMeta()}

function addBone(){if(!state.project)return;pushHistory();let base='bone',i=1;while(state.project.bones.some(b=>b.name===base+i))i++;const parent=state.selectedBone||null;state.project.bones.push({name:base+i,parent,length:40,x:0,y:0,rotation:0,scaleX:1,scaleY:1,shearX:0,shearY:0,transform:'normal',hidden:false,locked:false});state.selectedBone=base+i;renderAll()}
function duplicateBone(){const b=selected();if(!b)return;pushHistory();let n=b.name+'_copy',i=2;while(state.project.bones.some(x=>x.name===n))n=b.name+'_copy'+i++;state.project.bones.push({...deep(b),name:n,parent:b.parent});state.selectedBone=n;renderAll()}
function deleteBone(){const b=selected();if(!b)return;pushHistory();state.project.bones=state.project.bones.filter(x=>x.name!==b.name);state.project.bones.forEach(x=>{if(x.parent===b.name)x.parent=b.parent});state.selectedBone=b.parent||state.project.bones[0]?.name||null;renderAll()}
function addCurrentKey(){const b=selected();if(!b)return;pushHistory();const a=state.project.activeAnimation;state.project.customKeys[a]??={};state.project.customKeys[a][b.name]??=[];const arr=state.project.customKeys[a][b.name],pose={x:b.x,y:b.y,rotation:b.rotation,scaleX:b.scaleX,scaleY:b.scaleY,length:b.length};const old=arr.find(k=>Math.abs(k.time-state.currentTime)<1e-4);if(old)old.pose=pose;else arr.push({time:state.currentTime,pose});arr.sort((x,y)=>x.time-y.time);renderTimeline()}
function mirrorPose(){if(!state.project)return;pushHistory();for(const b of state.project.bones){b.x=-b.x;b.rotation=180-b.rotation;if(/^L_|_L_|Left/i.test(b.name)){const pair=b.name.replace(/L_/i,'R_').replace(/Left/i,'Right'),other=state.project.bones.find(x=>x.name===pair);if(other){const tmp={...b};Object.assign(b,{x:-other.x,y:other.y,rotation:180-other.rotation});Object.assign(other,{x:-tmp.x,y:tmp.y,rotation:180-tmp.rotation})}}}renderAll()}
function makeSnapshot(){state.snapshots.push({id:uid(),name:state.project.activeAnimation+' '+state.currentTime.toFixed(3),pose:deep(worldPose(state.currentTime)),time:state.currentTime});state.reference=state.snapshots.at(-1);renderInspector()}
function poseScore(){if(!state.reference)return 0;const cur=worldPose(state.currentTime),ref=new Map(state.reference.pose.map(b=>[b.name,b]));let sum=0,n=0;for(const b of cur){const r=ref.get(b.name);if(!r)continue;const dist=Math.hypot(b.wx-r.wx,b.wy-r.wy);let ad=Math.abs(((b.wr-r.wr+180)%360)-180);sum+=Math.exp(-dist/55)*.7+Math.exp(-ad/35)*.3;n++}return n?Math.round(sum/n*100):0}

function blankHumanoid(){const b=(name,parent,x,y,len,rot=0)=>({name,parent,x,y,length:len,rotation:rot,scaleX:1,scaleY:1,shearX:0,shearY:0,transform:'normal'});return normalizeProject({name:'Humanoid 新工程',bones:[b('root',null,0,0,0),b('pelvis','root',0,90,35,90),b('spine','pelvis',35,0,50,15),b('chest','spine',50,0,45,-15),b('neck','chest',42,0,18,0),b('head','neck',18,0,28,0),b('upper_arm_L','chest',35,20,45,145),b('forearm_L','upper_arm_L',45,0,42,10),b('hand_L','forearm_L',42,0,18,0),b('upper_arm_R','chest',35,-20,45,-145),b('forearm_R','upper_arm_R',45,0,42,-10),b('hand_R','forearm_R',42,0,18,0),b('thigh_L','pelvis',8,12,62,-95),b('shin_L','thigh_L',62,0,58,-2),b('foot_L','shin_L',58,0,25,82),b('thigh_R','pelvis',8,-12,62,-85),b('shin_R','thigh_R',62,0,58,2),b('foot_R','shin_R',58,0,25,88)],animations:{Pose:{bones:{}}},durations:{Pose:1}},'Humanoid 新工程')}
function newProjectModal(){$('#modal').innerHTML=`<h2>新建骨骼工程</h2><div class="two"><div class="case-card" id="humanoidPreset"><div class="case-title">Humanoid 2D</div><div class="case-meta">标准躯干 / 四肢层级，可立即改造</div></div><div class="case-card" id="emptyPreset"><div class="case-title">空白工程</div><div class="case-meta">只有 root，从零创建</div></div></div><div class="actions"><button data-close>取消</button></div>`;showModal();$('#humanoidPreset').onclick=()=>{loadProject(blankHumanoid());hideModal()};$('#emptyPreset').onclick=()=>{loadProject(normalizeProject({name:'空白工程',bones:[{name:'root',parent:null,x:0,y:0,length:50,rotation:0,scaleX:1,scaleY:1}],animations:{Pose:{bones:{}}},durations:{Pose:1}},'空白工程'));hideModal()};wireClose()}
function showHelp(){$('#modal').innerHTML=`<h2>Rig Motion Lab</h2><div class="note">这是面向 2D 骨骼动作学习与编辑的浏览器工作室。内置案例来自你上传的 Spine 3.5.51 阿米娅工程，网页端解析骨骼层级与骨骼动画轨道。<br><br><b>常用操作</b><br>• 鼠标滚轮：缩放；中键/Alt+左键：平移；左键关节：选择/拖动。<br>• Space：播放/暂停；←/→：逐帧；F：适配视图。<br>• Inspector 可直接改 Setup 参数，“◆ 当前帧”写入非破坏覆盖关键帧。<br>• 导入 ZIP 时会自动寻找其中所有 Spine JSON，并让你选择导入哪个工程。<br>• 保存写入浏览器 IndexedDB；导出生成可迁移的 Rig Motion Lab JSON。<br><br><b>兼容边界</b><br>当前工作室精确处理骨骼层级和 rotate/translate/scale/shear 时间线，用于动作学习和骨骼编辑；mesh/deform/slot draw-order 仍保留在原始 Spine 文件中，不在骨骼画布里做贴图网格编辑。</div><div class="actions"><button data-close class="primary">知道了</button></div>`;showModal();wireClose()}
function showModal(){$('#modalWrap').classList.add('show')}function hideModal(){$('#modalWrap').classList.remove('show')}function wireClose(){$$('[data-close]').forEach(b=>b.onclick=hideModal)}

async function importFiles(files){const arr=[...files];if(!arr.length)return;for(const f of arr){if(f.name.toLowerCase().endsWith('.zip')){const z=await JSZip.loadAsync(f);const entries=[];for(const [name,e] of Object.entries(z.files)){if(!e.dir&&name.toLowerCase().endsWith('.json')){try{const txt=await e.async('text'),d=JSON.parse(txt);if(d.bones&&d.animations)entries.push({name,data:d})}catch{}}}if(!entries.length){alert('ZIP 中没有识别到 Spine JSON');continue}if(entries.length===1)loadProject(normalizeProject(entries[0].data,entries[0].name));else chooseZip(entries);return}if(f.name.toLowerCase().endsWith('.json')){try{const d=JSON.parse(await f.text());loadProject(normalizeProject(d,d.name||f.name))}catch(e){alert('JSON 解析失败：'+e.message)}return}}
}
function chooseZip(entries){$('#modal').innerHTML=`<h2>ZIP 中发现 ${entries.length} 个骨骼工程</h2><div>${entries.map((e,i)=>`<div class="case-card" data-z="${i}"><div class="case-title">${esc(e.name)}</div><div class="case-meta"><span class="badge">${e.data.bones?.length||0} bones</span><span class="badge">${Object.keys(e.data.animations||{}).length} clips</span></div></div>`).join('')}</div><div class="actions"><button data-close>取消</button></div>`;showModal();$$('[data-z]').forEach(x=>x.onclick=()=>{loadProject(normalizeProject(entries[+x.dataset.z].data,entries[+x.dataset.z].name));hideModal()});wireClose()}
async function saveProject(){if(!state.project)return;state.project.updatedAt=Date.now();await dbPut(deep(state.project));$('#saveState').textContent='已保存 '+new Date().toLocaleTimeString();if(state.leftTab==='projects')renderLeft()}
function exportProject(){if(!state.project)return;const blob=new Blob([JSON.stringify(state.project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.project.name||'rig-project').replace(/[\\/:*?"<>|]+/g,'_')+'.rig.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

canvas.addEventListener('wheel',e=>{e.preventDefault();const before=toWorld(e.offsetX,e.offsetY),factor=Math.exp(-e.deltaY*.001);state.view.zoom=clamp(state.view.zoom*factor,.05,20);const after=toWorld(e.offsetX,e.offsetY);state.view.x+=(after[0]-before[0])*state.view.zoom;state.view.y-=(after[1]-before[1])*state.view.zoom},{passive:false});
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);if(e.button===1||e.altKey){state.drag={type:'pan',x:e.clientX,y:e.clientY,vx:state.view.x,vy:state.view.y};return}const b=hitBone(e.offsetX,e.offsetY);if(b){state.selectedBone=b.name;renderLeft();renderInspector();renderTimeline();const bone=selected();if(!bone?.locked){pushHistory();state.drag={type:'bone',bone,start:toWorld(e.offsetX,e.offsetY),x:bone.x,y:bone.y}}}else state.drag={type:'pan',x:e.clientX,y:e.clientY,vx:state.view.x,vy:state.view.y}});
canvas.addEventListener('pointermove',e=>{if(!state.drag)return;if(state.drag.type==='pan'){state.view.x=state.drag.vx+e.clientX-state.drag.x;state.view.y=state.drag.vy+e.clientY-state.drag.y}else{const b=state.drag.bone,w=toWorld(e.offsetX,e.offsetY),dx=w[0]-state.drag.start[0],dy=w[1]-state.drag.start[1];if(b.parent){const p=worldPose(state.currentTime).find(x=>x.name===b.parent);if(p){const rr=-rad(p.wr),lx=Math.cos(rr)*dx-Math.sin(rr)*dy,ly=Math.sin(rr)*dx+Math.cos(rr)*dy;b.x=state.drag.x+lx/(p.wsx||1);b.y=state.drag.y+ly/(p.wsy||1)}}else{b.x=state.drag.x+dx;b.y=state.drag.y+dy}renderInspector()}});canvas.addEventListener('pointerup',()=>state.drag=null);

function setupDrop(){const z=$('#dropZone');if(!z)return;['dragenter','dragover'].forEach(n=>z.addEventListener(n,e=>{e.preventDefault();z.classList.add('drag')}));['dragleave','drop'].forEach(n=>z.addEventListener(n,e=>{e.preventDefault();z.classList.remove('drag')}));z.addEventListener('drop',e=>importFiles(e.dataTransfer.files))}

$$('[data-left]').forEach(b=>b.onclick=()=>{$$('[data-left]').forEach(x=>x.classList.toggle('active',x===b));state.leftTab=b.dataset.left;renderLeft()});$$('[data-ins]').forEach(b=>b.onclick=()=>{$$('[data-ins]').forEach(x=>x.classList.toggle('active',x===b));state.insTab=b.dataset.ins;renderInspector()});
$('#leftSearch').oninput=renderLeft;$('#newBtn').onclick=newProjectModal;$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>importFiles(e.target.files);$('#saveBtn').onclick=saveProject;$('#exportBtn').onclick=exportProject;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#helpBtn').onclick=showHelp;$('#fitBtn').onclick=fitView;$('#gridBtn').onclick=()=>{state.showGrid=!state.showGrid;$('#gridBtn').textContent='网格 '+(state.showGrid?'✓':'')};$('#namesBtn').onclick=()=>{state.showNames=!state.showNames;$('#namesBtn').textContent='骨名 '+(state.showNames?'✓':'')};$('#onionBtn').onclick=()=>{state.onion=!state.onion;$('#onionBtn').textContent='洋葱皮 '+(state.onion?'✓':'')};$('#animSelect').onchange=e=>{state.project.activeAnimation=e.target.value;state.currentTime=0;renderAll()};$('#speedSelect').onchange=e=>state.speed=+e.target.value;$('#playBtn').onclick=()=>{state.playing=!state.playing;renderMeta()};$('#timeRange').oninput=e=>{state.currentTime=+e.target.value;renderTimeline();renderInspector()};$('#fpsInput').onchange=e=>{state.fps=clamp(+e.target.value||30,1,120);renderInspector()};$('#prevFrame').onclick=()=>{state.currentTime=clamp(state.currentTime-1/state.fps,0,duration());renderTimeline();renderInspector()};$('#nextFrame').onclick=()=>{state.currentTime=clamp(state.currentTime+1/state.fps,0,duration());renderTimeline();renderInspector()};$('#addKeyBtn').onclick=addCurrentKey;
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();state.playing=!state.playing;renderMeta()}else if(e.key==='f'||e.key==='F')fitView();else if(e.key==='ArrowLeft')$('#prevFrame').click();else if(e.key==='ArrowRight')$('#nextFrame').click();else if(e.key==='Delete')deleteBone();else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}});
function tick(t){if(state.playing&&state.project){if(!state.lastT)state.lastT=t;state.currentTime+=(t-state.lastT)/1000*state.speed;const d=duration();if(state.currentTime>d){if(state.loop)state.currentTime=d?state.currentTime%d:0;else{state.currentTime=d;state.playing=false}}renderMeta();if(Math.floor(t/80)!==Math.floor(state.lastT/80))renderTimeline()}state.lastT=t;requestAnimationFrame(tick)}
window.addEventListener('resize',()=>resizeCanvas());
loadManifest().then(async()=>{const locals=await dbAll();if(locals.length)loadProject(locals.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0]);else if(state.manifest.length)loadCase(state.manifest.find(c=>c.id==='amiya-default-front')||state.manifest[0])});renderAll();requestAnimationFrame(draw);requestAnimationFrame(tick);
