const MANUAL_JOBS=window.JOB_DATA||[];
const AUTO_JOBS=window.AUTO_JOB_DATA||[];
const TARGETS=window.COMPANY_TARGETS||[];
const JOBS=(()=>{const out=[],seen=new Set();for(const j of [...MANUAL_JOBS,...AUTO_JOBS]){const k=((j.applyUrl||"")+"|"+(j.title||"")+"|"+(j.company||"")).toLowerCase();if(!seen.has(k)){seen.add(k);out.push(j)}}return out})();
const CFG=window.SUPABASE_CONFIG||{};
const cloudConfigured=!!(CFG.url&&CFG.anonKey&&!CFG.url.startsWith("YOUR_")&&!CFG.anonKey.startsWith("YOUR_"));
const sb=cloudConfigured?window.supabase.createClient(CFG.url,CFG.anonKey):null;
let session=null,mine={},authMode="login",onlyMine=false,noteJobId=null,currentDetailId=null,currentView="jobs",deadlineDirection="asc";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function normalizeStage(s){if(!s||s==="未申请")return"未申请";if(["被拒","已拒绝","已放弃"].includes(s))return"被拒";return"已申请"}
function myState(id){const r=mine[id]||{stage:"未申请",note:""};return{...r,stage:normalizeStage(r.stage)}}
function tracked(id){const s=myState(id);return s.stage!=="未申请"||!!s.note}
function daysLeft(s){if(!s)return null;const d=new Date(s+"T00:00:00"),n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate());return Math.ceil((b-a)/86400000)}
function fmtDate(s){if(!s)return"待定";const d=new Date(s+"T00:00:00");return`${d.getMonth()+1}月${d.getDate()}日`}
function isVerified(j){if(j.verified===true)return true;if(j.auto===true&&j.verified!==true)return false;return/官方|集团官网|官方招聘|官方 Careers|官方校园招聘|官方公告|招聘官网/.test(j.source||"")}
function initials(n){return String(n||"企").replace(/中国|集团|股份有限公司|有限公司|科技|能源/g,"").slice(0,2)||"企"}
function deadlineMeta(j){const d=daysLeft(j.deadline);return{expired:d!==null&&d<0,urgent:d!==null&&d>=0&&d<=7}}
function compact(s,n=145){s=String(s||"");return s.length>n?s.slice(0,n)+"…":s}

function localUsers(){return JSON.parse(localStorage.getItem("jt_local_users_v1")||"{}")}
function localSessionEmail(){return localStorage.getItem("jt_local_session_v1")||""}
function localDataKey(e){return"jt_apps_v2:"+e.toLowerCase()}
function bytesHex(a){return[...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function sha256(t){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return bytesHex(new Uint8Array(b))}
async function localSignup(email,pw){const e=email.trim().toLowerCase(),u=localUsers();if(u[e])throw new Error("这个邮箱已注册，请直接登录。");const salt=bytesHex(crypto.getRandomValues(new Uint8Array(16)));u[e]={salt,hash:await sha256(salt+"|"+pw)};localStorage.setItem("jt_local_users_v1",JSON.stringify(u));localStorage.setItem("jt_local_session_v1",e);session={user:{id:"local:"+await sha256(e),email:e}}}
async function localLogin(email,pw){const e=email.trim().toLowerCase(),u=localUsers()[e];if(!u)throw new Error("本浏览器没有这个账号，请先注册。");if(await sha256(u.salt+"|"+pw)!==u.hash)throw new Error("密码不正确。");localStorage.setItem("jt_local_session_v1",e);session={user:{id:"local:"+await sha256(e),email:e}}}
function localLogout(){localStorage.removeItem("jt_local_session_v1");session=null;mine={}}
function loadLocalMine(){mine=session?JSON.parse(localStorage.getItem(localDataKey(session.user.email))||"{}"):{}}
function saveLocalMine(){if(session)localStorage.setItem(localDataKey(session.user.email),JSON.stringify(mine))}
async function initSession(){if(cloudConfigured){const{data}=await sb.auth.getSession();session=data.session;await loadMine();sb.auth.onAuthStateChange(async(_e,s)=>{session=s;await loadMine();updateUserUI();renderAll()})}else{const e=localSessionEmail();if(e){session={user:{id:"local:"+await sha256(e),email:e}};loadLocalMine()}}updateUserUI()}
async function loadMine(){mine={};if(!session)return;if(!cloudConfigured){loadLocalMine();return}const{data}=await sb.from("user_applications").select("job_id,stage,note,updated_at");(data||[]).forEach(r=>mine[r.job_id]=r)}
async function saveState(id,patch){if(!session){openAuth();return false}const c=myState(id),row={job_id:id,stage:patch.stage??c.stage,note:patch.note??c.note??""};if(!cloudConfigured){mine[id]={...row,updated_at:new Date().toISOString()};saveLocalMine();renderAll();return true}const{data,error}=await sb.from("user_applications").upsert({...row,user_id:session.user.id},{onConflict:"user_id,job_id"}).select().single();if(error)return false;mine[id]=data;renderAll();return true}
async function deleteState(id){if(!session)return;if(!cloudConfigured){delete mine[id];saveLocalMine();$("#noteDialog").close();renderAll();return}await sb.from("user_applications").delete().eq("user_id",session.user.id).eq("job_id",id);delete mine[id];$("#noteDialog").close();renderAll()}

const REGIONS=["北京","上海","天津","重庆","广东","江苏","浙江","湖北","湖南","四川","陕西","山东","安徽","福建","河南","河北","江西","辽宁","吉林","黑龙江","广西","云南","贵州","海南","山西","内蒙古","甘肃","青海","宁夏","新疆","西藏","海外","全国"];
function regionOf(j){const s=j.location||"";const h=REGIONS.filter(r=>s.includes(r));if(h.length)return h;if(/全国|多地|按岗位/.test(s))return["全国"];return s&&s!=="待核验"?[s]:["待核验"]}
function degreePass(j,v){if(!v)return true;const s=j.degree||"";if(v==="本科")return/本科|大学本科/.test(s);if(v==="硕士")return/硕士|研究生/.test(s);if(v==="博士")return/博士/.test(s);return true}
function fillFilters(){const tracks=[...new Set(JOBS.flatMap(j=>j.tracks||[]))].sort((a,b)=>a.localeCompare(b,"zh"));$("#trackFilter").innerHTML='<option value="">全部方向</option>'+tracks.map(x=>`<option>${esc(x)}</option>`).join("");const regions=[...new Set(JOBS.flatMap(regionOf))];$("#regionFilter").innerHTML='<option value="">全部地区</option>'+REGIONS.filter(x=>regions.includes(x)).concat(regions.filter(x=>!REGIONS.includes(x))).map(x=>`<option>${esc(x)}</option>`).join("");const sectors=[...new Set(TARGETS.map(x=>x.sector))].sort((a,b)=>a.localeCompare(b,"zh"));$("#sectorFilter").innerHTML='<option value="">全部行业</option>'+sectors.map(x=>`<option>${esc(x)}</option>`).join("")}

function filteredJobs(){
 const q=$("#searchInput").value.trim().toLowerCase(),track=$("#trackFilter").value,region=$("#regionFilter").value,degree=$("#degreeFilter").value,stage=$("#stageFilter").value,source=$("#sourceFilter").value,type=$("#typeFilter").value,showExpired=$("#showExpired").checked,sort=$("#sortFilter").value;
 const list=JOBS.filter(j=>{const hay=[j.company,j.unit,j.title,j.location,j.degree,j.majors,j.requirements,j.note,j.source,...(j.tracks||[])].join(" ").toLowerCase(),m=deadlineMeta(j),st=myState(j.id).stage;return(!q||hay.includes(q))&&(!track||(j.tracks||[]).includes(track))&&(!region||regionOf(j).includes(region))&&degreePass(j,degree)&&(!stage||st===stage)&&(!source||(source==="verified"?isVerified(j):!isVerified(j)))&&(!type||j.type===type)&&(!onlyMine||tracked(j.id))&&(showExpired||!m.expired)});
 list.sort((a,b)=>{if(sort==="updated-desc")return String(b.updated||"").localeCompare(String(a.updated||""));if(sort==="company-asc")return String(a.company).localeCompare(String(b.company),"zh");const ad=daysLeft(a.deadline),bd=daysLeft(b.deadline),av=ad===null?99998:(ad<0?99999:ad),bv=bd===null?99998:(bd<0?99999:bd);return deadlineDirection==="asc"?av-bv:bv-av});return list
}
function renderJobs(){
 const list=filteredJobs();$("#jobRows").innerHTML=list.map(j=>{const m=deadlineMeta(j),st=myState(j.id),v=isVerified(j);return`<tr>
 <td><div class="deadline"><b>${esc(fmtDate(j.deadline))}</b>${m.urgent?'<em>即将截止</em>':""}</div></td>
 <td><div class="company-cell"><div class="logo">${esc(initials(j.company))}</div><div><div class="company-name">${esc(j.company)}</div><div class="job-title">${esc(j.title)}</div><div class="sub">${esc(j.unit||"")}</div><div class="tags">${(j.tracks||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></div></div></td>
 <td><b>${esc(j.location||"待核验")}</b><div class="sub">更新 ${esc(j.updated||"—")}</div></td>
 <td class="edu"><b>${esc(j.degree||"待核验")}</b><div class="sub">${esc(j.majors||"待核验")}</div></td>
 <td class="req"><div class="clamp">${esc(compact(j.requirements))}</div></td>
 <td class="source-cell"><span class="source-badge ${v?"ok":"web"}">${v?"官方 / 已核验":"全网发现"}</span><a class="btn ${v?"primary":"light"}" target="_blank" rel="noopener" href="${esc(j.applyUrl)}">${v?"投递":"来源"} ↗</a></td>
 <td><div class="status-actions"><button class="status-btn apply ${st.stage==="已申请"?"active":""}" data-status="已申请" data-job="${j.id}" title="已申请">✓</button><button class="status-btn reject ${st.stage==="被拒"?"active":""}" data-status="被拒" data-job="${j.id}" title="被拒">✕</button><button class="status-btn note ${st.note?"active":""}" data-note="${j.id}" title="备注">✎</button></div></td>
 <td><button class="detail-btn" data-detail="${j.id}">详情</button></td></tr>`}).join("");
 $("#resultCount").textContent=list.length;$("#emptyState").classList.toggle("hidden",list.length>0);$("#deadlineArrow").textContent=deadlineDirection==="asc"?"↑":"↓";bindRowActions()
}
function companyRows(){
 const counts={};for(const j of JOBS)counts[j.company]=(counts[j.company]||0)+1;
 const union=[...TARGETS];for(const name of Object.keys(counts)){if(!union.some(x=>x.name===name))union.push({id:"job-"+name,name,sector:"其他",tags:[]})}
 const q=$("#searchInput").value.trim().toLowerCase(),sector=$("#sectorFilter").value,status=$("#companyStatusFilter").value,sort=$("#companySortFilter").value;
 const rows=union.map(c=>({...c,jobs:counts[c.name]||0})).filter(c=>(!q||[c.name,c.sector,...(c.tags||[])].join(" ").toLowerCase().includes(q))&&(!sector||c.sector===sector)&&(!status||(status==="hasJobs"?c.jobs>0:c.jobs===0)));
 rows.sort((a,b)=>sort==="name-asc"?a.name.localeCompare(b.name,"zh"):(b.jobs-a.jobs||a.name.localeCompare(b.name,"zh")));return rows
}
function renderCompanies(){
 const rows=companyRows();$("#companyGrid").innerHTML=rows.map(c=>`<article class="company-card" data-company="${esc(c.name)}"><div class="company-top"><span class="sector">${esc(c.sector)}</span><span class="${c.jobs?"has-jobs":"pending"}">${c.jobs?c.jobs+" 条岗位":"待扫描"}</span></div><h3>${esc(c.name)}</h3><div class="company-tags">${esc((c.tags||[]).join(" · "))}</div><div class="company-bottom"><span>${c.jobs?"查看岗位":"加入扫描范围"}</span><span class="company-arrow">→</span></div></article>`).join("");$("#companyResultCount").textContent=rows.length;$("#companyEmpty").classList.toggle("hidden",rows.length>0);$$("[data-company]").forEach(x=>x.onclick=()=>{const name=x.dataset.company;setView("jobs");$("#searchInput").value=name;renderAll();window.scrollTo({top:0,behavior:"smooth"})})
}
function renderStats(){const names=new Set([...TARGETS.map(x=>x.name),...JOBS.map(x=>x.company)]);$("#totalCount").textContent=JOBS.length;$("#companyCount").textContent=names.size;$("#jobsTabCount").textContent=JOBS.length;$("#companiesTabCount").textContent=names.size;if(session){const vals=Object.values(mine).map(x=>normalizeStage(x.stage));$("#appliedCount").textContent=vals.filter(x=>x==="已申请").length;$("#rejectedCount").textContent=vals.filter(x=>x==="被拒").length}else{$("#appliedCount").textContent="—";$("#rejectedCount").textContent="—"}}
function renderAll(){renderStats();if(currentView==="jobs")renderJobs();else renderCompanies()}

function setView(v){currentView=v;const jobs=v==="jobs";$("#jobsView").classList.toggle("hidden",!jobs);$("#companiesView").classList.toggle("hidden",jobs);$("#jobFilters").classList.toggle("hidden",!jobs);$("#companyFilters").classList.toggle("hidden",jobs);$("#advancedFilters").classList.add("hidden");$("#moreFiltersBtn").textContent="筛选";$("#jobsTab").classList.toggle("active",jobs);$("#companiesTab").classList.toggle("active",!jobs);$("#viewTitle").textContent=jobs?"岗位库":"企业库";$("#viewSubtitle").textContent=jobs?"土木本专业、能源、新能源、CAE、汽车机械转行都放进来。默认隐藏已截止岗位。":"先把值得关注的企业全部放进池子，再由自动扫描持续补岗位。";$("#searchInput").placeholder=jobs?"搜索企业、岗位、地区、专业、技能、要求……":"搜索企业、行业、方向……";renderAll()}
function bindRowActions(){$$("[data-status]").forEach(x=>x.onclick=async()=>{if(!session){openAuth();return}const id=x.dataset.job,w=x.dataset.status;await saveState(id,{stage:myState(id).stage===w?"未申请":w})});$$("[data-note]").forEach(x=>x.onclick=()=>{if(!session){openAuth();return}openNote(x.dataset.note)});$$("[data-detail]").forEach(x=>x.onclick=()=>openDetail(x.dataset.detail))}
function openNote(id){noteJobId=id;const j=JOBS.find(x=>x.id===id);$("#noteTitle").textContent=(j?.company||"岗位")+" · 备注";$("#noteText").value=myState(id).note||"";$("#noteDialog").showModal()}
function openDetail(id){currentDetailId=id;const j=JOBS.find(x=>x.id===id);if(!j)return;const d=daysLeft(j.deadline);$("#detailTitle").textContent=j.title;$("#detailCompany").textContent=(j.company||"")+" · "+(j.unit||"");$("#detailContent").innerHTML=[["地点",j.location||"待核验"],["学历",j.degree||"待核验"],["专业",j.majors||"待核验"],["人数",j.headcount||"未公开"],["开始",j.openDate||"未公开"],["截止",j.deadline?(j.deadline+(d!==null&&d>=0&&d<=7?" · 即将截止":"")):"未公布"],["方向",(j.tracks||[]).join(" / ")],["来源",j.source||""],["要求",j.requirements||""],["流程",j.process||""],["备注",j.note||"—"]].map((x,i)=>`<div class="detail-item ${i>=8?"full":""}"><label>${esc(x[0])}</label><div>${esc(x[1])}</div></div>`).join("");$("#detailApply").href=j.applyUrl;$("#detailSource").href=j.sourceUrl||j.applyUrl;$("#detailNoteBtn").classList.toggle("hidden",!session);$("#detailDialog").showModal()}
function updateUserUI(){const on=!!session;$("#loginBtn").classList.toggle("hidden",on);$("#userBox").classList.toggle("hidden",!on);if(on){$("#userName").textContent=session.user.email;$("#syncStatus").textContent=cloudConfigured?"云端账户":"本机账户"}else $("#syncStatus").textContent="未登录 · 浏览模式"}
function setAuthMode(m){authMode=m;$("#tabLogin").classList.toggle("active",m==="login");$("#tabSignup").classList.toggle("active",m==="signup");$("#authSubmit").textContent=m==="login"?"登录":"注册";$("#authMessage").textContent=""}
function openAuth(){setAuthMode("login");$("#authModeHint").textContent=cloudConfigured?"云端账号，可跨设备同步":"当前为本机账户，仅当前浏览器保存";$("#authFine").textContent=cloudConfigured?"每个用户只能读取自己的记录。":"请不要使用其他重要网站的相同密码。";$("#authDialog").showModal()}
async function submitAuth(){const email=$("#authEmail").value.trim(),pw=$("#authPassword").value,msg=$("#authMessage");if(!email.includes("@")||pw.length<6){msg.textContent="请输入有效邮箱，密码至少6位。";return}try{if(cloudConfigured){const r=authMode==="signup"?await sb.auth.signUp({email,password:pw,options:{emailRedirectTo:location.origin+location.pathname}}):await sb.auth.signInWithPassword({email,password:pw});if(r.error)throw r.error;if(authMode==="signup"&&!r.data.session){msg.textContent="注册成功，请检查邮箱完成验证。";return}session=r.data.session;await loadMine()}else{if(authMode==="signup")await localSignup(email,pw);else await localLogin(email,pw);loadLocalMine()}$("#authDialog").close();updateUserUI();renderAll()}catch(e){msg.textContent=e.message||String(e)}}
function resetFilters(){["searchInput","trackFilter","regionFilter","degreeFilter","stageFilter","sourceFilter","typeFilter","sectorFilter","companyStatusFilter"].forEach(id=>{const e=$("#"+id);if(e)e.value=""});$("#sortFilter").value="deadline-asc";$("#companySortFilter").value="jobs-desc";$("#showExpired").checked=false;onlyMine=false;deadlineDirection="asc";renderAll()}
function bindStatic(){$("#jobsTab").onclick=()=>setView("jobs");$("#companiesTab").onclick=()=>setView("companies");$("#themeBtn").onclick=()=>{const n=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=n;localStorage.setItem("jt-theme",n)};$("#loginBtn").onclick=openAuth;$("#logoutBtn").onclick=async()=>{if(cloudConfigured)await sb.auth.signOut();else{localLogout();updateUserUI();renderAll()}};$("#tabLogin").onclick=()=>setAuthMode("login");$("#tabSignup").onclick=()=>setAuthMode("signup");$("#authSubmit").onclick=submitAuth;$("#authPassword").addEventListener("keydown",e=>{if(e.key==="Enter")submitAuth()});["searchInput","trackFilter","regionFilter","degreeFilter","stageFilter","sortFilter","sourceFilter","typeFilter","showExpired","sectorFilter","companyStatusFilter","companySortFilter"].forEach(id=>{const e=$("#"+id);e.addEventListener(e.tagName==="INPUT"&&e.type==="text"?"input":"change",renderAll)});$("#moreFiltersBtn").onclick=()=>{$("#advancedFilters").classList.toggle("hidden");$("#moreFiltersBtn").textContent=$("#advancedFilters").classList.contains("hidden")?"筛选":"收起"};$("#onlyMineBtn").onclick=()=>{onlyMine=!onlyMine;$("#onlyMineBtn").textContent=onlyMine?"✓ 只看已标记":"只看已标记";renderAll()};$("#resetBtn").onclick=resetFilters;$("#deadlineSortBtn").onclick=()=>{deadlineDirection=deadlineDirection==="asc"?"desc":"asc";$("#sortFilter").value="deadline-asc";renderJobs()};$$("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$("#saveNoteBtn").onclick=async()=>{if(noteJobId){const ok=await saveState(noteJobId,{note:$("#noteText").value.trim()});if(ok)$("#noteDialog").close()}};$("#deleteStateBtn").onclick=async()=>{if(noteJobId&&confirm("确定删除这个岗位的个人记录吗？"))await deleteState(noteJobId)};$("#detailNoteBtn").onclick=()=>{if(currentDetailId){$("#detailDialog").close();openNote(currentDetailId)}}}
async function init(){document.documentElement.dataset.theme=localStorage.getItem("jt-theme")||"light";fillFilters();bindStatic();await initSession();setView("jobs")}
init();